window.translations = {
    ...window.translations,
    en: {
        ...(window.translations?.en || {}),
        "profile-nick": "Nick",
        "nav-main": "Main",
        "nav-profile": "Profile",
        "nav-create": "Create",
        "nav-saves": "Saves",
        "nav-settings": "Settings",
        "nav-rules": "Rules",
        "nav-faq": "FAQ",
        "nav-back": "← Back",
        "create-title": "Create new fanfic",
        "create-fanficname": "Fanfic name:",
        "create-size": "Size:",
        "size-drabble-label": "Drabble",
        "size-mini-label": "Mini",
        "size-midi-label": "Midi",
        "size-maxi-label": "Maxi",
        "create-categories": "Categories:",
        "cat-romance": "Romance",
        "cat-angst": "Angst",
        "cat-comedy": "Comedy",
        "cat-drama": "Drama",
        "cat-hurt-comfort": "Hurt/Comfort",
        "cat-pov": "POV",
        "cat-pwp": "PWP",
        "cat-dystopia": "Dystopia",
        "cat-dark-fiction": "Dark fiction",
        "cat-detective": "Detective",
        "cat-friendship": "Friendship",
        "cat-curtain-story": "Curtain story",
        "cat-evil-author": "Evil author",
        "cat-historical-epochs": "Historical epochs",
        "cat-love-hate": "Love/Hate",
        "cat-time-travel": "Time travel",
        "cat-omegaverse": "Omegaverse",
        "cat-parody": "Parody",
        "cat-first-time": "First time",
        "cat-slice-of-life": "Slice of life",
        "cat-isekai": "Isekai",
        "cat-post-apocalyptic": "Post-Apocalyptic",
        "cat-omitted-scene": "Omitted scene",
        "cat-psychology": "Psychology",
        "cat-soulmates": "Soulmates",
        "cat-banter": "Banter",
        "cat-horror": "Horror",
        "cat-school-life": "School life",
        "cat-sci-fi": "Sci-fi",
        "cat-philosophy": "Philosophy",
        "cat-puff": "Puff",
        "cat-experiment": "Experiment",
        "cat-action": "Action",
        "cat-ooc": "OOC",
        "cat-ofp": "OFP",
        "cat-omp": "OMP",
        "features": "Features:",
        "POV": "POV",
        "AU": "AU",
        "Fourth-Wall": "Fourth wall",
        "Age-ratings": "Age ratings:",
        "age-G-label": "G",
        "age-PG-13-label": "PG-13",
        "age-R-label": "R",
        "age-NC-17-label": "NC-17",
        "age-NC-21-label": "NC-21",
        "Status": "Status:",
        "Abandoned-label": "Abandoned",
        "Frozen-label": "Frozen",
        "Announced-label": "Announced",
        "Finished-label": "Finished",
        "In-Progress-label": "In Progress",
        "annotation-text": "Annotation text:",
        "create-mature": "Contains mature content (18+)",
        "create-cover": "Cover image:",
        "create-text": "Fanfic text:",
        "create-button": "Create"
    },
    ru: {
        ...(window.translations?.ru || {}),
        "profile-nick": "Ник",
        "nav-main": "Главная",
        "nav-profile": "Профиль",
        "nav-create": "Создать",
        "nav-saves": "Закладки",
        "nav-settings": "Настройки",
        "nav-rules": "Правила",
        "nav-faq": "FAQ",
        "nav-back": "← Назад",
        "create-title": "Создать новый фанфик",
        "create-fanficname": "Название фанфика:",
        "create-size": "Размер:",
        "size-drabble-label": "Драббл",
        "size-mini-label": "Мини",
        "size-midi-label": "Миди",
        "size-maxi-label": "Макси",
        "create-categories": "Категории:",
        "cat-romance": "Романтика",
        "cat-angst": "Ангст",
        "cat-comedy": "Комедия",
        "cat-drama": "Драма",
        "cat-hurt-comfort": "Hurt/Comfort",
        "cat-pov": "POV",
        "cat-pwp": "PWP",
        "cat-dystopia": "Антиутопия",
        "cat-dark-fiction": "Тёмное произведение",
        "cat-detective": "Детектив",
        "cat-friendship": "Дружба",
        "cat-curtain-story": "Занавесочная история",
        "cat-evil-author": "Злой автор",
        "cat-historical-epochs": "Исторические эпохи",
        "cat-love-hate": "Любовь/Ненависть",
        "cat-time-travel": "Путешествие во времени",
        "cat-omegaverse": "Омегаверс",
        "cat-parody": "Пародия",
        "cat-first-time": "Первый раз",
        "cat-slice-of-life": "Повседневность",
        "cat-isekai": "Исекай",
        "cat-post-apocalyptic": "Постапокалипсис",
        "cat-omitted-scene": "Пропущенная сцена",
        "cat-psychology": "Психология",
        "cat-soulmates": "Родственные души",
        "cat-banter": "Подшучивание",
        "cat-horror": "Ужасы",
        "cat-school-life": "Школьная жизнь",
        "cat-sci-fi": "Научная фантастика",
        "cat-philosophy": "Философия",
        "cat-puff": "Пафф",
        "cat-experiment": "Эксперимент",
        "cat-action": "Экшн",
        "cat-ooc": "OOC",
        "cat-ofp": "OFP",
        "cat-omp": "OMP",
        "features": "Особенности:",
        "POV": "POV",
        "AU": "AU",
        "Fourth-Wall": "Четвёртая стена",
        "Age-ratings": "Возрастные рейтинги:",
        "age-G-label": "G",
        "age-PG-13-label": "PG-13",
        "age-R-label": "R",
        "age-NC-17-label": "NC-17",
        "age-NC-21-label": "NC-21",
        "Status": "Статус:",
        "Abandoned-label": "Заброшен",
        "Frozen-label": "Заморожен",
        "Announced-label": "Анонсирован",
        "Finished-label": "Завершён",
        "In-Progress-label": "В процессе",
        "annotation-text": "Текст аннотации:",
        "create-mature": "Содержит материалы 18+",
        "create-cover": "Обложка:",
        "create-text": "Текст фанфика:",
        "create-button": "Создать"
    },
    es: {
        ...(window.translations?.es || {}),
        "profile-nick": "Apodo",
        "nav-main": "Principal",
        "nav-profile": "Perfil",
        "nav-create": "Crear",
        "nav-saves": "Guardados",
        "nav-settings": "Configuración",
        "nav-rules": "Reglas",
        "nav-faq": "FAQ",
        "nav-back": "← Volver",
        "create-title": "Crear nuevo fanfic",
        "create-fanficname": "Nombre del fanfic:",
        "create-size": "Tamaño:",
        "size-drabble-label": "Drabble",
        "size-mini-label": "Mini",
        "size-midi-label": "Midi",
        "size-maxi-label": "Maxi",
        "create-categories": "Categorías:",
        "cat-romance": "Romance",
        "cat-angst": "Angustia",
        "cat-comedy": "Comedia",
        "cat-drama": "Drama",
        "cat-hurt-comfort": "Hurt/Comfort",
        "cat-pov": "POV",
        "cat-pwp": "PWP",
        "cat-dystopia": "Distopía",
        "cat-dark-fiction": "Ficción oscura",
        "cat-detective": "Detectivesco",
        "cat-friendship": "Amistad",
        "cat-curtain-story": "Historia de telón",
        "cat-evil-author": "Autor malvado",
        "cat-historical-epochs": "Épocas históricas",
        "cat-love-hate": "Amor/Odio",
        "cat-time-travel": "Viaje en el tiempo",
        "cat-omegaverse": "Omegaverse",
        "cat-parody": "Parodia",
        "cat-first-time": "Primera vez",
        "cat-slice-of-life": "Vida cotidiana",
        "cat-isekai": "Isekai",
        "cat-post-apocalyptic": "Post-apocalíptico",
        "cat-omitted-scene": "Escena omitida",
        "cat-psychology": "Psicología",
        "cat-soulmates": "Almas gemelas",
        "cat-banter": "Bromas",
        "cat-horror": "Terror",
        "cat-school-life": "Vida escolar",
        "cat-sci-fi": "Ciencia ficción",
        "cat-philosophy": "Filosofía",
        "cat-puff": "Puff",
        "cat-experiment": "Experimento",
        "cat-action": "Acción",
        "cat-ooc": "OOC",
        "cat-ofp": "OFP",
        "cat-omp": "OMP",
        "features": "Características:",
        "POV": "POV",
        "AU": "UA",
        "Fourth-Wall": "Cuarta pared",
        "Age-ratings": "Clasificación por edad:",
        "age-G-label": "G",
        "age-PG-13-label": "PG-13",
        "age-R-label": "R",
        "age-NC-17-label": "NC-17",
        "age-NC-21-label": "NC-21",
        "Status": "Estado:",
        "Abandoned-label": "Abandonado",
        "Frozen-label": "Congelado",
        "Announced-label": "Anunciado",
        "Finished-label": "Terminado",
        "In-Progress-label": "En progreso",
        "annotation-text": "Texto de anotación:",
        "create-mature": "Contiene contenido maduro (18+)",
        "create-cover": "Imagen de portada:",
        "create-text": "Texto del fanfic:",
        "create-button": "Crear"
    },
    ja: {
        ...(window.translations?.ja || {}),
        "profile-nick": "ニックネーム",
        "nav-main": "メイン",
        "nav-profile": "プロフィール",
        "nav-create": "作成",
        "nav-saves": "保存",
        "nav-settings": "設定",
        "nav-rules": "ルール",
        "nav-faq": "FAQ",
        "nav-back": "← 戻る",
        "create-title": "新しいファンフィクを作成",
        "create-fanficname": "ファンフィク名:",
        "create-size": "サイズ:",
        "size-drabble-label": "ドラブル",
        "size-mini-label": "ミニ",
        "size-midi-label": "ミディ",
        "size-maxi-label": "マキシ",
        "create-categories": "カテゴリー:",
        "cat-romance": "ロマンス",
        "cat-angst": "アングスト",
        "cat-comedy": "コメディ",
        "cat-drama": "ドラマ",
        "cat-hurt-comfort": "ハート/コンフォート",
        "cat-pov": "POV",
        "cat-pwp": "PWP",
        "cat-dystopia": "ディストピア",
        "cat-dark-fiction": "ダークフィクション",
        "cat-detective": "探偵",
        "cat-friendship": "友情",
        "cat-curtain-story": "カーテンストーリー",
        "cat-evil-author": "悪の作者",
        "cat-historical-epochs": "歴史的時代",
        "cat-love-hate": "愛/憎",
        "cat-time-travel": "タイムトラベル",
        "cat-omegaverse": "オメガバース",
        "cat-parody": "パロディ",
        "cat-first-time": "初めて",
        "cat-slice-of-life": "日常",
        "cat-isekai": "異世界",
        "cat-post-apocalyptic": "ポストアポカリプス",
        "cat-omitted-scene": "省略されたシーン",
        "cat-psychology": "心理学",
        "cat-soulmates": "ソウルメイト",
        "cat-banter": "バンター",
        "cat-horror": "ホラー",
        "cat-school-life": "学校生活",
        "cat-sci-fi": "SF",
        "cat-philosophy": "哲学",
        "cat-puff": "パフ",
        "cat-experiment": "実験",
        "cat-action": "アクション",
        "cat-ooc": "OOC",
        "cat-ofp": "OFP",
        "cat-omp": "OMP",
        "features": "特徴:",
        "POV": "POV",
        "AU": "AU",
        "Fourth-Wall": "第四の壁",
        "Age-ratings": "年齢制限:",
        "age-G-label": "G",
        "age-PG-13-label": "PG-13",
        "age-R-label": "R",
        "age-NC-17-label": "NC-17",
        "age-NC-21-label": "NC-21",
        "Status": "ステータス:",
        "Abandoned-label": "放棄",
        "Frozen-label": "凍結",
        "Announced-label": "発表済み",
        "Finished-label": "完了",
        "In-Progress-label": "進行中",
        "annotation-text": "注釈テキスト:",
        "create-mature": "成人向けコンテンツを含む (18+)",
        "create-cover": "カバー画像:",
        "create-text": "ファンフィク本文:",
        "create-button": "作成"
    },
    fr: {
        ...(window.translations?.fr || {}),
        "profile-nick": "Pseudo",
        "nav-main": "Accueil",
        "nav-profile": "Profil",
        "nav-create": "Créer",
        "nav-saves": "Favoris",
        "nav-settings": "Paramètres",
        "nav-rules": "Règles",
        "nav-faq": "FAQ",
        "nav-back": "← Retour",
        "create-title": "Créer une nouvelle fanfic",
        "create-fanficname": "Nom de la fanfic:",
        "create-size": "Taille:",
        "size-drabble-label": "Drabble",
        "size-mini-label": "Mini",
        "size-midi-label": "Midi",
        "size-maxi-label": "Maxi",
        "create-categories": "Catégories:",
        "cat-romance": "Romance",
        "cat-angst": "Angoisse",
        "cat-comedy": "Comédie",
        "cat-drama": "Drame",
        "cat-hurt-comfort": "Hurt/Comfort",
        "cat-pov": "POV",
        "cat-pwp": "PWP",
        "cat-dystopia": "Dystopie",
        "cat-dark-fiction": "Fiction sombre",
        "cat-detective": "Policier",
        "cat-friendship": "Amitié",
        "cat-curtain-story": "Histoire de rideau",
        "cat-evil-author": "Auteur maléfique",
        "cat-historical-epochs": "Époques historiques",
        "cat-love-hate": "Amour/Haine",
        "cat-time-travel": "Voyage dans le temps",
        "cat-omegaverse": "Omegaverse",
        "cat-parody": "Parodie",
        "cat-first-time": "Première fois",
        "cat-slice-of-life": "Tranche de vie",
        "cat-isekai": "Isekai",
        "cat-post-apocalyptic": "Post-apocalyptique",
        "cat-omitted-scene": "Scène omise",
        "cat-psychology": "Psychologie",
        "cat-soulmates": "Âmes sœurs",
        "cat-banter": "Taquinerie",
        "cat-horror": "Horreur",
        "cat-school-life": "Vie scolaire",
        "cat-sci-fi": "Science-fiction",
        "cat-philosophy": "Philosophie",
        "cat-puff": "Puff",
        "cat-experiment": "Expérimental",
        "cat-action": "Action",
        "cat-ooc": "OOC",
        "cat-ofp": "OFP",
        "cat-omp": "OMP",
        "features": "Caractéristiques:",
        "POV": "POV",
        "AU": "UA",
        "Fourth-Wall": "Quatrième mur",
        "Age-ratings": "Classification d'âge:",
        "age-G-label": "G",
        "age-PG-13-label": "PG-13",
        "age-R-label": "R",
        "age-NC-17-label": "NC-17",
        "age-NC-21-label": "NC-21",
        "Status": "Statut:",
        "Abandoned-label": "Abandonné",
        "Frozen-label": "Gelé",
        "Announced-label": "Annoncé",
        "Finished-label": "Terminé",
        "In-Progress-label": "En cours",
        "annotation-text": "Texte d'annotation:",
        "create-mature": "Contient du contenu mature (18+)",
        "create-cover": "Image de couverture:",
        "create-text": "Texte de la fanfic:",
        "create-button": "Créer"
    }
};



document.addEventListener('DOMContentLoaded', () => {
    const createForm = document.querySelector('.create-form');

    if (!createForm) {
        return;
    }

    createForm.addEventListener('submit', async (event) => {
        event.preventDefault();
        const title = document.getElementById('fanfic-title').value;
        const content = document.getElementById('fanfic-content').value;
        const author = getCurrentUser() || 'Anonymous'; 
        const result = await createFanfic(title, author, content);
        if (result && result.status === 'success') {
            alert('Фанфик успешно создан!');
            window.location.href = 'index.html';
        } else {
            alert('Ошибка при создании фанфика: ' + (result.message || 'Неизвестная ошибка'));
        }
    });
});
