window.translations = {
    ...window.translations, 
    en: {
        ...(window.translations?.en || {}),
        "rules-title": "Site Rules",
        "rules-general": "General Rules:",
        "rules-general-1": "Respect other users",
        "rules-general-2": "Do not post spam",
        "rules-general-3": "Follow age restrictions",
        "rules-general-4": "Credit original authors",
        "rules-general-5": "No plagiarism",
        "rules-content": "Content Rules:",
        "rules-content-1": "Properly tag mature content",
        "rules-content-2": "No illegal content",
        "rules-content-3": "Respect fandom-specific rules",
        "rules-content-4": "Provide warnings for triggering content",
        "rules-publishing": "Publishing Rules:",
        "rules-publishing-1": "One fanfic per publication",
        "rules-publishing-2": "Use appropriate categories",
        "rules-publishing-3": "Minimum 500 characters for fanfics",
        "rules-publishing-4": "Provide accurate size classification"
    },
    ru: {
        ...(window.translations?.ru || {}),
        "rules-title": "Правила сайта",
        "rules-general": "Общие правила:",
        "rules-general-1": "Уважайте других пользователей",
        "rules-general-2": "Не публикуйте спам",
        "rules-general-3": "Соблюдайте возрастные ограничения",
        "rules-general-4": "Указывайте оригинальных авторов",
        "rules-general-5": "Запрещён плагиат",
        "rules-content": "Правила контента:",
        "rules-content-1": "Правильно помечайте контент для взрослых",
        "rules-content-2": "Запрещён незаконный контент",
        "rules-content-3": "Уважайте правила конкретных фандомов",
        "rules-content-4": "Предупреждайте о триггерном контенте",
        "rules-publishing": "Правила публикации:",
        "rules-publishing-1": "Один фанфик на публикацию",
        "rules-publishing-2": "Используйте соответствующие категории",
        "rules-publishing-3": "Минимум 500 символов для фанфиков",
        "rules-publishing-4": "Указывайте точную классификацию по размеру"
    },
    es: {
        ...(window.translations?.es || {}),
        "rules-title": "Reglas del sitio",
        "rules-general": "Reglas generales:",
        "rules-general-1": "Respeta a otros usuarios",
        "rules-general-2": "No publiques spam",
        "rules-general-3": "Respeta las restricciones de edad",
        "rules-general-4": "Reconoce a los autores originales",
        "rules-general-5": "No al plagio",
        "rules-content": "Reglas de contenido:",
        "rules-content-1": "Etiqueta correctamente el contenido maduro",
        "rules-content-2": "Sin contenido ilegal",
        "rules-content-3": "Respeta las reglas específicas del fandom",
        "rules-content-4": "Advierte sobre contenido sensible",
        "rules-publishing": "Reglas de publicación:",
        "rules-publishing-1": "Un fanfic por publicación",
        "rules-publishing-2": "Usa categorías apropiadas",
        "rules-publishing-3": "Mínimo 500 caracteres para fanfics",
        "rules-publishing-4": "Proporciona una clasificación de tamaño precisa"
    },
    fr: {
        ...(window.translations?.fr || {}),
        "rules-title": "Règles du site",
        "rules-general": "Règles générales :",
        "rules-general-1": "Respectez les autres utilisateurs",
        "rules-general-2": "Ne publiez pas de spam",
        "rules-general-3": "Respectez les restrictions d'âge",
        "rules-general-4": "Créditez les auteurs originaux",
        "rules-general-5": "Pas de plagiat",
        "rules-content": "Règles de contenu :",
        "rules-content-1": "Étiquetez correctement le contenu pour adultes",
        "rules-content-2": "Pas de contenu illégal",
        "rules-content-3": "Respectez les règles spécifiques aux fandoms",
        "rules-content-4": "Avertissez en cas de contenu sensible",
        "rules-publishing": "Règles de publication :",
        "rules-publishing-1": "Une fanfic par publication",
        "rules-publishing-2": "Utilisez des catégories appropriées",
        "rules-publishing-3": "Minimum 500 caractères pour les fanfics",
        "rules-publishing-4": "Fournissez une classification de taille précise"
    },
    ja: {
        ...(window.translations?.ja || {}),
        "rules-title": "サイトルール",
        "rules-general": "一般ルール：",
        "rules-general-1": "他のユーザーを尊重する",
        "rules-general-2": "スパムを投稿しない",
        "rules-general-3": "年齢制限を守る",
        "rules-general-4": "原作者のクレジットを表示",
        "rules-general-5": "盗作禁止",
        "rules-content": "コンテンツルール：",
        "rules-content-1": "アダルトコンテンツは適切にタグ付けする",
        "rules-content-2": "違法コンテンツ禁止",
        "rules-content-3": "ファンダム固有のルールを尊重する",
        "rules-content-4": "トリガーとなるコンテンツには警告を表示",
        "rules-publishing": "公開ルール：",
        "rules-publishing-1": "一度に一つのファンフィクを公開",
        "rules-publishing-2": "適切なカテゴリーを使用する",
        "rules-publishing-3": "ファンフィクは最低500文字以上",
        "rules-publishing-4": "正確なサイズ分類を提供する"
    }
};

window.translations = {
    ...window.translations,
    en: {
        ...(window.translations?.en || {}),
        "profile-nick": "Nick",
        "nav-main": "Main",
        "nav-profile": "Profile",
        "nav-create": "Create",
        "nav-saves": "Saves",
        "nav-settings": "Settings",
        "nav-rules": "Rules",
        "nav-faq": "FAQ",
        "nav-back": "← Back"
    },
    ru: {
        ...(window.translations?.ru || {}),
        "profile-nick": "Ник",
        "nav-main": "Главная",
        "nav-profile": "Профиль",
        "nav-create": "Создать",
        "nav-saves": "Сохраненное",
        "nav-settings": "Настройки",
        "nav-rules": "Правила",
        "nav-faq": "ЧаВо",
        "nav-back": "← Назад"
    },
    es: {
        ...(window.translations?.es || {}),
        "profile-nick": "Apodo",
        "nav-main": "Principal",
        "nav-profile": "Perfil",
        "nav-create": "Crear",
        "nav-saves": "Guardados",
        "nav-settings": "Ajustes",
        "nav-rules": "Reglas",
        "nav-faq": "FAQ",
        "nav-back": "← Atrás"
    },
    fr: {
        ...(window.translations?.fr || {}),
        "profile-nick": "Pseudo",
        "nav-main": "Accueil",
        "nav-profile": "Profil",
        "nav-create": "Créer",
        "nav-saves": "Sauvegardes",
        "nav-settings": "Paramètres",
        "nav-rules": "Règles",
        "nav-faq": "FAQ",
        "nav-back": "← Retour"
    },
    ja: {
        ...(window.translations?.ja || {}),
        "profile-nick": "ニックネーム",
        "nav-main": "メイン",
        "nav-profile": "プロフィール",
        "nav-create": "作成",
        "nav-saves": "保存済み",
        "nav-settings": "設定",
        "nav-rules": "ルール",
        "nav-faq": "FAQ",
        "nav-back": "← 戻る"
    }
};

